version: "3.8"

services:
  redis:
    image: redis
    container_name: redis_cache
    networks:
      - internal

  app:
    build: .
    container_name: lifeline_backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - REDIS_URI=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - internal
    restart: always

networks:
  internal:
    driver: bridge
